### ISSUE TITLE
[POST] Apollo Server 2 and TypeScript

### ISSUE THREAD

**Issue by swashata** [swashata/swas.io#9]
Install apollo server and dependencies

https://www.apollographql.com/docs/apollo-server/getting-started.html

Install Graphql Code Generator for resolvers

https://graphql-code-generator.com/docs/plugins/typescript-resolvers

Config like 

```yml
overwrite: true
schema: "./schema.graphql"
documents: null
generates:
  ./generated/gql-gen/graphql.ts:
    plugins:
      - "typescript-common"
      - "typescript-server"
      - "typescript-resolvers"
```

🎉
